apiVersion: v1
kind: Service
metadata:
  name: ait-service
spec:
  selector:
    app: ait
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30500